import { describe, expect, it } from 'vitest';

const plugin = require('./android-nano-clarification');
const {
  ENABLED_PROPERTY,
  MIN_SDK_PROPERTY,
  BASE_MIN_SDK_PROPERTY,
  applyNanoMinSdkProperties,
  injectMinSdkGuard,
  resolveNanoClarificationEnabled,
  upsertGradleProperty,
} = plugin.__testables;

describe('android-nano-clarification config plugin', () => {
  it('enables only an explicit non-FOSS development evaluation', () => {
    expect(resolveNanoClarificationEnabled({
      requested: true,
      appVariant: 'development',
      fossBuild: false,
    })).toBe(true);
    expect(resolveNanoClarificationEnabled({
      requested: false,
      appVariant: 'development',
      fossBuild: false,
    })).toBe(false);
    expect(resolveNanoClarificationEnabled({
      requested: true,
      appVariant: 'production',
      fossBuild: false,
    })).toBe(false);
    expect(resolveNanoClarificationEnabled({
      requested: true,
      appVariant: 'development',
      fossBuild: true,
    })).toBe(false);
  });

  it('persists one matching Gradle property', () => {
    const entries = [{ type: 'property', key: ENABLED_PROPERTY, value: 'false' }];
    upsertGradleProperty(entries, ENABLED_PROPERTY, 'true');
    upsertGradleProperty(entries, ENABLED_PROPERTY, 'true');

    expect(entries).toEqual([{ type: 'property', key: ENABLED_PROPERTY, value: 'true' }]);
  });

  it('raises and restores only the evaluation-owned minimum-SDK floor', () => {
    const entries = [{ type: 'property', key: MIN_SDK_PROPERTY, value: '24' }];
    applyNanoMinSdkProperties(entries, true);

    expect(entries).toEqual([
      { type: 'property', key: MIN_SDK_PROPERTY, value: '26' },
      { type: 'property', key: BASE_MIN_SDK_PROPERTY, value: '24' },
    ]);

    applyNanoMinSdkProperties(entries, false);
    expect(entries).toEqual([{ type: 'property', key: MIN_SDK_PROPERTY, value: '24' }]);
  });

  it('preserves an independently raised minimum SDK', () => {
    const entries = [
      { type: 'property', key: MIN_SDK_PROPERTY, value: '28' },
      { type: 'property', key: BASE_MIN_SDK_PROPERTY, value: '24' },
    ];

    applyNanoMinSdkProperties(entries, false);

    expect(entries).toEqual([{ type: 'property', key: MIN_SDK_PROPERTY, value: '28' }]);
  });

  it('injects an idempotent conditional API 26 floor', () => {
    const source = 'buildscript {}\napply plugin: "expo-root-project"\n';
    const once = injectMinSdkGuard(source);
    const twice = injectMinSdkGuard(once);

    expect(twice).toBe(once);
    expect(once).toContain("findProperty('mindwtrNanoEnabled')");
    expect(once).toContain('ext.minSdkVersion = Math.max');
    expect(once).toContain(', 26)');
    expect(once).toContain("configuration.name.endsWith('CompileClasspath')");
    expect(once).toContain("force 'org.jetbrains.kotlin:kotlin-stdlib:2.1.20'");
    expect(once.match(/@generated by mindwtr-android-nano-clarification start/g)).toHaveLength(1);
  });
});
